name: Boost Brakeman Demo
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    types:
      - opened
      - synchronize

jobs:
  scanner:
    name: boost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute boost-brakeman-demo
        uses: boostsecurityio/boostsec-scanner-github@v4.1
        with:
          registry_module: scanners/boostsecurityio/brakeman-scanner-demo
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          api_endpoint: https://api.dev.boostsec.io
          additional_args: --registry https://github.com/boostsecurityio/scanner-registry.git#update-brakeman-image-and-rules
