name: Boost Brakeman Scanner
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  scan_job:
    name: Boost Brakeman Scanner
    env:
      BOOST_SCANNER_REGISTRY_REPO_DEV: https://github.com/boostsecurityio/scanner-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Boost Brakeman Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4.0.2
        with:
          registry_module: scanners/boostsecurityio/brakeman-scanner
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          api_endpoint: https://api.dev.boostsec.io
